name: Build New Image

on:
  push:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.new_version }}
      version_tag: ${{ steps.semver.outputs.new_tag }}
      commit: ${{ env.GITHUB_SHA }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Bump version and push tag
      id: semver
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: main,develop
      
    - name: Debug Version
      continue-on-error: true
      run: |
        echo "Output of version: ${{ steps.semver.outputs.new_version }}"
        echo "Output of version_tag: ${{ steps.semver.outputs.new_tag }}"

  create_github_tag:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create release entry on GitHub
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: false
          tag: ${{ needs.build.outputs.version_tag }}
          commit: ${{ needs.build.outputs.commit }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
  
  create_docker_tag:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create docker release
        run: docker build . --file Dockerfile --tag dhoeppner/website:${{ needs.build.outputs.version }}
        
      - name: Upload to docker hub
        run: docker push dhoeppner/website:${{ needs.build.outputs.version }}

